// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/print/:slug": {
    params: {
      "slug": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/coding": {
    params: {};
  };
  "/prints": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/print/:slug" | "/sitemap.xml" | "/coding" | "/prints" | "/robots.txt" | "/*";
  };
  "routes/[print].$slug._index.tsx": {
    id: "routes/[print].$slug._index";
    page: "/print/:slug";
  };
  "routes/[sitemap.xml]._index.tsx": {
    id: "routes/[sitemap.xml]._index";
    page: "/sitemap.xml";
  };
  "routes/[coding]._index.tsx": {
    id: "routes/[coding]._index";
    page: "/coding";
  };
  "routes/[prints]._index.tsx": {
    id: "routes/[prints]._index";
    page: "/prints";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/[print].$slug._index": typeof import("./app/routes/[print].$slug._index.tsx");
  "routes/[sitemap.xml]._index": typeof import("./app/routes/[sitemap.xml]._index.tsx");
  "routes/[coding]._index": typeof import("./app/routes/[coding]._index.tsx");
  "routes/[prints]._index": typeof import("./app/routes/[prints]._index.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};